# Generated by Django 4.0 on 2024-02-17 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_chats_f', to='models_app.user', verbose_name='Первый участник')),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_chats_s', to='models_app.user', verbose_name='Второй участник')),
            ],
            options={
                'verbose_name': 'Direct chat',
                'verbose_name_plural': 'Direct chats',
                'db_table': 'direct_chats',
            },
        ),
        migrations.AddConstraint(
            model_name='directchat',
            constraint=models.UniqueConstraint(fields=('first_user', 'second_user'), name='unique_first_user_second_user'),
        ),
    ]
