# Generated by Django 4.0 on 2024-04-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_directchat_encrypted_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='directchat',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
