# Generated by Django 4.0 on 2024-04-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0007_directchat_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directchat',
            old_name='encrypted_key',
            new_name='hasher_symmetric_key',
        ),
        migrations.AddField(
            model_name='directchat',
            name='is_private',
            field=models.BooleanField(default=1, verbose_name='Приватный чат?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(default=1, max_length=255, verbose_name='Публичный ключ'),
            preserve_default=False,
        ),
    ]
