# Generated by Django 4.0 on 2024-05-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0009_alter_user_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directchat',
            name='hasher_symmetric_key',
            field=models.TextField(max_length=255, verbose_name='Зашифрованный симметричный ключ'),
        ),
    ]
